### ISSUE TITLE
[RFC] simple VHDCI carrier

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/meta#20]
@jordens @hartytp @dhslichter I finished extension boards for Banker and an idea came to my mind. We can make simple LVDS VHDCI to EDGE connector converter. In this way we can use BNC/SMA/DSUB adapters directly with FMC-VHDCI or Metlino once it becomes available. In this way up to 32 simple IOs can be connected directly without VHDCI carrier + EEM IOs.
I don't know if it is worth the effort since it duplicates the EEM idea.

**Comment by jordens** [comment]
The modules are really nice. I guess doing 4 edge connectors on each side would have been a bit crowded.
About the lvds vhdci to edge converter I personally am a bit hesitant. It's nice for really simple DIO from sayma/metlino/kc705 and similar. But probably people would primarily go for the existing solutions since it is extensible and more powerful.

**Comment by dhslichter** [comment]
I think the existing EEM DIO breakout boards are fine from my point of view, although this is a nice idea.
